#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t 9p -o trans=virtio,version=9p2000.L,nosuid hostshare /home/ctf
#for f in $(ls *.ko); do
#    insmod $f
#done
sysctl -w kernel.perf_event_paranoid=1

chmod 600 /flag
chown 0.0 /flag

insmod proc_leak.ko
insmod bof_module.ko

su -l ctf -c "cd / && exec ./hangman"
